name: google_calendar
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  http: ^0.13.6
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  simple_logger: ^1.9.0+2
  syncfusion_flutter_calendar: ^21.2.5
  go_router: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto_Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: NotoSansJP_Bold
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
    - family: NotoSansJP_Medium
      fonts:
        - asset: assets/fonts/NotoSansJP-Medium.otf
    - family: NotoSansJP_Regular
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
